// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-05-15",
  devtools: { enabled: true },

  // modules: [
  //   '@nuxtjs/tailwindcss',
  //   '@nuxt/content',
  //   '@nuxtjs/color-mode',
  //   '@nuxtjs/supabase',
  //   '@nuxtjs/robots',
  //   '@nuxtjs/redirect-module',
  //   '@nuxtjs/gtm',
  //   '@nuxtjs/sitemap',
  //   '@nuxtjs/analytics',
  //   '@nuxtjs/recaptcha',
  //   '@nuxtjs/markdownit',
  //   '@nuxtjs/axios',
  //   '@nuxtjs/pwa',
  //   '@nuxtjs/strapi',
  //   '@nuxtjs/algolia',
  //   '@nuxtjs/laravel-echo',
  //   '@nuxtjs/laravel-echo-socket-io',
  //   '@nuxtjs/laravel-echo-pusher',
  //   '@nuxtjs/laravel-echo-pusher-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket',
  //   '@nuxtjs/laravel-echo-pusher-websocket-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-socket-io',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-socket-io',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-socket-io',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-socket-io',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-js',
  //   '@nuxtjs/laravel-echo-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-pusher-websocket-socket-io',
  // ],
  // css: [
  //   '@/assets/css/main.css',
  //   '@/assets/css/tailwind.css',
  //   '@/assets/css/typography.css',
  //   '@/assets/css/colors.css',
  //   '@/assets/css/animations.css',
  //   '@/assets/css/variables.css',
  //   '@/assets/css/fonts.css',
  //   '@/assets/css/buttons.css',
  //   '@/assets/css/forms.css',
  //   '@/assets/css/layout.css',
  //   '@/assets/css/responsive.css',
  //   '@/assets/css/transitions.css',
  //   '@/assets/css/shadows.css',
  //   '@/assets/css/badge.css',
  // ],
  // app: {
  //   head: {
  //     title: 'Badge Design Layer',
  //     meta: [
  //       { name: 'viewport', content: 'width=device-width, initial-scale=1' },
  //       { name: 'description', content: 'Design your own badges with ease' },
  //       { name: 'keywords', content: 'badges, design, customization, graphics' },
  //       { name: 'author', content: 'BadgeFnd Team' },
  //       { name: 'theme-color', content: '#ffffff' },
  //     ],
  //     link: [
  //       { rel: 'icon', type: 'image/png', href: '/favicon.png' },
  //       { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' },
  //       { rel: 'manifest', href: '/manifest.json' },
  //       { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap' },
  //       { rel: 'stylesheet', href: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css' },
  //     ],
  //     script: [
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.5.2/js/bootstrap.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.12/vue.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/vue-router/3.5.2/vue-router.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/vuex/3.6.2/vuex.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt/2.15.8/nuxt.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-i18n/6.15.0/nuxt-i18n.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-content/1.15.0/nuxt-content.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-axios/5.13.6/nuxt-axios.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-pwa/3.3.0/nuxt-pwa.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-strapi/1.3.0/nuxt-strapi.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-algolia/1.2.0/nuxt-algolia.min.js', body: true },
  //       { src: 'https://cdnjs.cloudflare.com/ajax/libs/nuxt-laravel-echo/1.0.0/nuxt-laravel-echo.min.js', body: true },
  //     ],
  //   },
  // },
  // content: {
  //   highlight: {
  //     theme: {
  //       default: 'github-light',
  //       dark: 'github-dark',
  //     },
  //   },
  //   markdown: {
  //     remarkPlugins: ['remark-emoji', 'remark-gfm'],
  //     rehypePlugins: ['rehype-katex'],
  //   },
  // },
  // colorMode: {
  //   classSuffix: '',
  //   preference: 'light',
  //   fallback: 'light',
  // },
  // robots: {
  //   UserAgent: '*',
  //   Disallow: '/admin',
  //   Allow: '/',
  // },
  // redirect: [
  //   { from: '^/old-path', to: '/new-path', statusCode: 301 },
  //   { from: '^/temporary-redirect', to: '/new-temporary-path', statusCode: 302 },
  // ],
  // gtm: {
  //   id: 'GTM-XXXXXX',
  //   enabled: true,
  //   debug: false,
  //   pageTracking: true,
  //   respectDoNotTrack: true,
  // },
  // sitemap: {
  //   hostname: 'https://badgefnd.com',
  //   gzip: true,
  //   routes: [
  //     '/about',
  //     '/contact',
  //     '/privacy-policy',
  //     '/terms-of-service',
  //     '/design-badge',
  //     '/design-badge/step1',
  //     '/design-badge/step2',
  //     '/design-badge/step3',
  //     '/design-badge/step4',
  //     '/design-badge/step5',
  //     '/design-badge/step6',
  //     '/design-badge/step7',
  //     '/design-badge/step8',
  //     '/design-badge/step9',
  //     '/design-badge/step10',
  //     '/design-badge/step11',
  //     '/design-badge/step12',
  //     '/design-badge/step13',
  //     '/design-badge/step14',
  //     '/design-badge/step15',
  //     '/design-badge/step16',
  //     '/design-badge/step17',
  //     '/design-badge/step18',
  //     '/design-badge/step19',
  //     '/design-badge/step20',
  //     '/design-badge/step21',
  //     '/design-badge/step22',
  //     '/design-badge/step23',
  //     '/design-badge/step24',
  //     '/design-badge/step25',
  //     '/design-badge/step26',
  //     '/design-badge/step27',
  //     '/design-badge/step28',
  //     '/design-badge/step29',
  //     '/design-badge/step30',
  //     '/design-badge/step31',
  //     '/design-badge/step32',
  //     '/design-badge/step33',
  //     '/design-badge/step34',
  //     '/design-badge/step35',
  //     '/design-badge/step36',
  //     '/design-badge/step37',
  //     '/design-badge/step38',
  //     '/design-badge/step39',
  //     '/design-badge/step40',
  //     '/design-badge/step41',
  //     '/design-badge/step42',
  //     '/design-badge/step43',
  //     '/design-badge/step44',
  //     '/design-badge/step45',
  //     '/design-badge/step46',
  //     '/design-badge/step47',
  //     '/design-badge/step48',
  //     '/design-badge/step49',
  //     '/design-badge/step50',
  //     '/design-badge/step51',
  //     '/design-badge/step52',
  //     '/design-badge/step53',
  //     '/design-badge/step54',
  //     '/design-badge/step55',
  //     '/design-badge/step56',
  //     '/design-badge/step57',
  //     '/design-badge/step58',
  //     '/design-badge/step59',
  //     '/design-badge/step60',
  //     '/design-badge/step61',
  //     '/design-badge/step62',
  //     '/design-badge/step63',
  //     '/design-badge/step64',
  //     '/design-badge/step65',
  //     '/design-badge/step66',
  //     '/design-badge/step67',
  //     '/design-badge/step68',
  //     '/design-badge/step69',
  //     '/design-badge/step70',
  //     '/design-badge/step71',
  //     '/design-badge/step72',
  //     '/design-badge/step73',
  //     '/design-badge/step74',
  //     '/design-badge/step75',
  //     '/design-badge/step76',
  //     '/design-badge/step77',
  //     '/design-badge/step78',
  //     '/design-badge/step79',
  //     '/design-badge/step80',
  //     '/design-badge/step81',
  //     '/design-badge/step82',
  //     '/design-badge/step83',
  //     '/design-badge/step84',
  //     '/design-badge/step85',
  //     '/design-badge/step86',
  //     '/design-badge/step87',
  //     '/design-badge/step88',
  //     '/design-badge/step89',
  //     '/design-badge/step90',
  //     '/design-badge/step91',
  //     '/design-badge/step92',
  //     '/design-badge/step93',
  //     '/design-badge/step94',
  //     '/design-badge/step95',
  //     '/design-badge/step96',
  //     '/design-badge/step97',
  //     '/design-badge/step98',
  //     '/design-badge/step99',
  //     '/design-badge/step100',
  //   ],
  // },
  // analytics: {
  //   id: 'UA-XXXXXX-X',
  //   debug: { enabled: true },
  //   autoTracking: {
  //     pageview: true,
  //     click: true,
  //     event: true,
  //     exception: true,
  //     timing: true,
  //   },
  // },
  // recaptcha: {
  //   siteKey: '6LeIxAcTAAAAAJcZVRqyHh712s9dQ6c5c5c5c5c',
  //   version: 'v2',
  //   size: 'normal', // 'compact' or 'normal'
  // },
  // markdownit: {
  //   preset: 'default',
  //   linkify: true,
  //   typographer: true,
  //   breaks: true,
  //   html: true,
  //   use: ['markdown-it-emoji', 'markdown-it-katex', 'markdown-it-anchor', 'markdown-it-toc-done-right', 'markdown-it-highlightjs'],
  // },
  // axios: {
  //   baseURL: 'https://api.badgefnd.com',
  //   credentials: true,
  //   headers: {
  //     common: {
  //       Accept: 'application/json',
  //       'Content-Type': 'application/json',
  //     },
  //     post: {
  //       'Content-Type': 'application/json',
  //     },
  //     put: {
  //       'Content-Type': 'application/json',
  //     },
  //     patch: {
  //       'Content-Type': 'application/json',
  //     },
  //     delete: {
  //       'Content-Type': 'application/json',
  //     },
  //   },
  // },
  // pwa: {
  //   manifest: {
  //     name: 'BadgeFnd',
  //     short_name: 'BadgeFnd',
  //     description: 'Design your own badges with ease',
  //     lang: 'en',
  //     display: 'standalone',
  //     theme_color: '#ffffff',
  //     background_color: '#ffffff',
  //     icons: [
  //       { src: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
  //       { src: '/icon-512x512.png', sizes: '512x512', type: 'image/png' },
  //       { src: '/icon-apple-touch.png', sizes: '180x180', type: 'image/png' },
  //       { src: '/icon-maskable.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
  //     ],
  //   },
  //   workbox: {
  //     enabled: true,
  //     runtimeCaching: [ {
  //       urlPattern: 'https://api.badgefnd.com/.*',
  //       handler: 'NetworkFirst',
  //       method: 'GET',
  //       strategyOptions: {
  //         cacheName: 'api-cache',
  //         cacheableResponse: {
  //           statuses: [200],
  //         },
  //       },
  //     } ],
  //   },
  // },
  // strapi: {
  //   url: 'https://api.badgefnd.com',
  //   entities: ['badges', 'users', 'comments', 'likes', 'shares'],
  //   version: 'v4',
  //   prefix: '/api',
  //   cookie: {
  //     name: 'strapi_jwt',
  //     options: { httpOnly: true, secure: true, sameSite: 'Lax' },
  //   },
  // },

  sourcemap: {
    server: true,
    client: true,
  },
  nitro: {
    preset: "node-server",
    prerender: {
      crawlLinks: true,
      failOnError: false,
    },
  },

  extends: ["./modules/designbadge"],
  modules: ["@nuxtjs/tailwindcss", "@nuxt/icon", '@vueuse/nuxt'],

  build: {
    transpile: ["qrcode"],
  },

  // plugins: ["~/modules/plugins/page-builder.client.ts"],
});